'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Avis
    Public Property Id As Integer
    Public Property Nom As String
    Public Property Description As String
    Public Property Note As Double
    Public Property IdFormation As Integer
    Public Property DateAvis As Date
    Public Property UserId As String

    Public Overridable Property Formation As Formation

End Class
