'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Formation
    Public Property Id As Integer
    Public Property Nom As String
    Public Property Url As String
    Public Property Description As String
    Public Property NomSeo As String

    Public Overridable Property Avis As ICollection(Of Avis) = New HashSet(Of Avis)

End Class
